### ISSUE TITLE
Access to trained checkpoints

### ISSUE THREAD

**Issue by ghost** [kk42yy/DACAT#1]
Hello,

Congratulations on this promising work and many thanks for sharing models and code!
I'm very excited to explore your method. Unfortunately, for some reason, I cannot access the Google drive where you stored your checkpoints. 
Could you make the Google drive accessible, please?

**Comment by kk42yy** [comment]
Hello funny-spark,
I just checked again and it was successfully downloaded using `Microsoft Edge` browser.
Best wishes

**Comment by ghost** [comment]
Thank you for your prompt response!
Maybe you are still logged in to your Google account in the browser?
Because I get the error message below:

![image](https://github.com/user-attachments/assets/3c3b1eb0-bd39-411e-bc09-4785245c4be8)

I guess you can reproduce the problem when you try to open the link to the Google drive in a new private window.

**Comment by kk42yy** [comment]
Sorry about that, it could be downloaded now.

**Comment by ghost** [comment]
Great, it worked! Thank you so much!
